### ISSUE TITLE
add custom 'fetch' support (as config param?)

### ISSUE THREAD

**Issue by lifeart** [developit/redaxios#16]
We have `isomorphic` fetch for ember - https://github.com/ember-cli/ember-fetch it working in node & browser to bring smooth SSR experience, I whould like to have redaxios, with ember-fetch support

**Comment by dlemper** [comment]
Would be interested, too, so that I can use it under node as well using node-fetch.
When I‘m back at my notebook, I can create a pull request though

**Comment by developit** [comment]
Any reason it's not possible to install your fetch polyfill globally? I realize it's not elegant, but `global.fetch=fetch` does work.

**Comment by lifeart** [comment]
@developit it's possible, but not clean and hard to mock/test/maintain

**Comment by developit** [comment]
I would definitely be interested in supporting this as long as the size impact is minimal. Adding it [here](https://github.com/developit/redaxios/blob/982fd7fe30189e662cda5b72f9b37c8f1babc038/src/index.js#L171) would make it configurable both per-instance (`axios.create({fetch})`) and per-request (`axios.get('',{fetch})`).

**Comment by crissto** [comment]
Hi!
Can I give this a try? Seems an easy, useful issue.

**Comment by developit** [comment]
Yeah, go ahead @crissto!

**Comment by lifeart** [comment]
@developit @crissto thank you for your work!
Any estimates about new release?

**Comment by developit** [comment]
Merged! will release today.

**Comment by developit** [comment]
Apologies for the wait! I spent too much time refactoring and shaving bytes off last week. Just published [version 0.3.0](https://github.com/developit/redaxios/releases/tag/0.3.0) which includes custom fetch support.
