### ISSUE TITLE
discrepancy in response data  

### ISSUE THREAD

**Issue by David5280** [developit/redaxios#21]
Hey there,

I'm trying to convert some axios requests to `redaxios` and I'm noticing a discrepancy in the responses.  The data object coming back from `redaxios` is stringified, whereas the data object I currently receive with `axios` is valid JSON. I am wondering if it would make sense to do this conversion in `redaxios` so that it is truly a drop-in replacement of axios?  

Looking forward to hearing your thoughts, thanks!

**Comment by developit** [comment]
Ah - I'm guessing Axios inspects the response headers and determines when JSON should be used rather than text. I think we can add that [here](https://github.com/developit/redaxios/blob/982fd7fe30189e662cda5b72f9b37c8f1babc038/src/index.js#L185). Good catch!

**Comment by hasan-wajahat** [comment]
Actually the default value for `responseType` in axios is `json`. So to match the API of axios, `redaxios` should do the same.

**Comment by developit** [comment]
Thanks for the tip @hasan-wajahat - I actually had read that wrong in the docs (I've never used Axios!). I amended the solution from #26 based on your comment.

This issue is now fixed in [version 0.3.0](https://github.com/developit/redaxios/releases/tag/0.3.0).
