### ISSUE TITLE
Params aren't serialized

### ISSUE THREAD

**Issue by tandrewnichols** [developit/redaxios#29]
Not sure what level of compatibility is the goal here (ala #14), but axios serializes `params` as query string parameters and redaxios doesn't. E.g.

```javascript
// With axios
axios.get('/blah', { params: { foo: 'bar' }}); // -> /blah?foo=bar

// With redaxios
axios.get('/blah', { params: { foo: 'bar' }}); // -> /blah
```

**Comment by developit** [comment]
I'd like to support this. It should be trivial to implement atop `URLSearchParams`.

**Comment by crissto** [comment]
This seems easy, I can send a PR if it's ok.
