### ISSUE TITLE
QUESTION: When can we expect a new release on npm registry?

### ISSUE THREAD

**Issue by hasan-wajahat** [developit/redaxios#43]
I am really looking forward to using this package on my production website but on the latest released version there is bug related to posting formdata. This bug has been resolved and the PR for it merged but there has not been release since this was done.
I tried using the github url in package.json but for some reason even though the package was added but the `dist` folder was never built. So I can't use it on my production site.
Can a new version be released soon so that I can continue to install through npm registry?

**Comment by developit** [comment]
Today! I just published [version 0.3.0](https://github.com/developit/redaxios/releases/tag/0.3.0).

**Comment by hasan-wajahat** [comment]
Thank you @developit for such a quick response!
