### ISSUE TITLE
Cannot use relative URL for the baseURL option

### ISSUE THREAD

**Issue by rschristian** [developit/redaxios#45]
(Using Preact-CLI's issue template as I find it easy to read)

**Do you want to request a _feature_ or report a _bug_?**

Likely a bug

**What is the current behavior?**

Currently Redaxios cannot use relative URLs for its `baseURL`. The `URL()` constructor, if passed a `base` parameter, needs that parameter to be a valid URL on its own, and a relative URL like `/api/` is not. [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).

**If the current behaviour is a bug, please provide the steps to reproduce.**

Simply open a browser console and write:

`new URL('foo', '/api/');` 

You will get an error stating the following:

`Uncaught TypeError: URL constructor: /foo/ is not a valid URL.`

That example is [how Redaxios currently forms its URLs](https://github.com/developit/redaxios/blob/3313c9f8210fea3564d0da844c654e8f9a4b89e0/src/index.js#L181) when a `baseURL` is supplied

**What is the expected behaviour?**

I'd like to be able to use relative URLs for the base as they're very handy for proxying front-end applications.

**Comment by mfix22** [comment]
If it helps, this PR reproduces the issue: https://github.com/carbon-app/carbon/pull/1054 (just open the "Background Image" menu w/ a debug point set in the `redaxios` try/catch)
