### ISSUE TITLE
Support for deno?

### ISSUE THREAD

**Issue by kingkong404** [developit/redaxios#54]
Would be great! Thanks!

**Comment by developit** [comment]
Any idea what this would entail? I've never used Deno, and Redaxios is currently browser-only. If Deno supports `fetch()` though, merging #57 should make redaxios work there.

**Comment by Stevenje** [comment]
@developit Yes, that was my thoughts exactly, Deno supports `fetch()` along with all other web browser API's out of the box so should be an easy migration. 

Then registering it with https://deno.land/x

**Comment by Stevenje** [comment]
https://dev.to/jotafeldmann/converting-a-node-project-to-deno-9dp

**Comment by cztomsik** [comment]
You just need to add file `/mod.ts` with `export * from './src/index.js'` and then go to https://deno.land/x and click on `Add a module` button
![image](https://user-images.githubusercontent.com/3526922/107118503-cb8cbc00-6881-11eb-8259-07c8296daf7e.png)

**Comment by developit** [comment]
... and we're live! version 0.5.0 is available for Deno now:
https://deno.land/x/redaxios
