### ISSUE TITLE
Usage on Deno

### ISSUE THREAD

**Issue by Loskir** [developit/redaxios#85]
How do I use it on Deno?

If I import it as `import axios from 'https://deno.land/x/redaxios@0.5.0/mod.ts'`, I get this error

```text
TS1192 [ERROR]: Module '"https://deno.land/x/redaxios@0.5.0/mod.ts"' has no default export.
import axios from 'https://deno.land/x/redaxios@0.5.0/mod.ts'
       ~~~~~
    at file:///...

TS1195 [ERROR]:     'export *' does not re-export a default.
    export * from './src/index.js'
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/redaxios@0.5.0/mod.ts:1:1

Found 2 errors.
```

And `./src/index.js` doesn't seem to have any other exports.

Deno version: 1.22.0

**Comment by christopheragnus** [comment]
Second this. I can't use it on Deno until this problem is fixed.

**Comment by wilt00** [comment]
If folks are still running into this issue, you can import from the unmerged `fix-deno` branch directly - currently, it's strictly ahead of 0.5.0, so you aren't missing out on any changes. I've just tested this:
```javascript
import axios from 'https://raw.githubusercontent.com/developit/redaxios/fix-deno/mod.ts';

axios.get('https://catfact.ninja/fact').then(console.log);
```
Probably not great for production use, but if you're running Deno in production, you're already using [`deno vendor`](https://deno.land/manual/tools/vendor), right? :D
