### ISSUE TITLE
Axios is adding a fetch adapter natively. Will Redaxios have any use then?

### ISSUE THREAD

**Issue by nickchomey** [developit/redaxios#93]
This PR seems close to completion for adding a Fetch Adapter. https://github.com/axios/axios/pull/5146

Will there be any need/use-case for Redaxios then? It seems like it would still be lighter-weight - is that because Redaxios is just pure Fetch, while Axios + Fetch Adapter would still have all of the XHR stuff built-in?

Thanks!

**Comment by rschristian** [comment]
Indeed, even with the adapter `redaxios` should continue to be much lighter than `axios`.

There is a bit of a feature difference between the two, `axios` provides a number of helpers and some data manipulation that *will* be carried over to the new fetch implementation from the sounds of it.

`redaxios` is (for some) a more comfortable API for interacting with `fetch()` while `axios` on the other hand is a bit more of an opinionated helper for making requests.

**Comment by nickchomey** [comment]
Thanks! Yeah, I came to realize that redaxios isn't really axios with fetch, but just fetch with axios' api/interface. It doesn't appear to have interceptors, for example - despite there seeming to be an outstanding PR for it.

In all likelihood I'll end up using ofetch or wretch for my project - fetch with some axios-like features.
